stages:
  - test
  - allure

Run Tests:
  tags:
    - bpmgroovyRunner2
  stage: test
  allow_failure: true
  script:
    - ./gradlew clean test
  artifacts:
    when: always
    paths:
      - build/allure-results

Allure report:
  stage: allure
  tags:
    - bpmgroovyRunner2
  script:
    - ./gradlew allureReport
    - echo "Allure report live here - https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/browse/build/reports/allure-report/allureReport/index.html"
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport